version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
    nodejs: "18"
  apt_packages:
    - libpci-dev

conda:
  environment: .readthedocs_env.yml

python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
