version: 2

build:
  image: latest
  apt_packages:
    - libpci-dev

# As of June 2021, We need to set up a conda environment to install
# a sufficiently new Node.js: https://github.com/readthedocs/readthedocs.org/issues/8249

conda:
  environment: .readthedocs_env.yml

python:
  version: 3.9
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py
