name: pywwt_rtd
channels:
  - conda-forge

dependencies:
  - astropy
  - astropy-sphinx-theme
  - ipyevents
  - ipykernel
  - ipywidgets
  - lxml
  - matplotlib
  - nbclassic
  - numpydoc
  - pip
  - pyopengl
  - pyqt
  - pyqtwebengine
  - python =3.10
  - qt
  - qtpy
  - reproject
  - setuptools
  - sphinx
  - sphinx-automodapi=0.16
