jobs:

- template: azure-template.yml
  parameters:
    name: Linux
    os: linux

- template: azure-template.yml
  parameters:
    name: Windows
    os: windows

# Don't test on MacOS X for now
# - template: azure-template.yml
#   parameters:
#     name: MacOSX
#     os: macosx
