# First stage of CI: create the `sdist` and Cranko release commit.

jobs:

- job: sdist
  pool:
    vmImage: ubuntu-20.04

  steps:

  - checkout: self

  - bash: |
      set -euo pipefail
      d="$(mktemp -d /tmp/cranko.XXXXXX)"
      cd "$d"
      curl --proto '=https' --tlsv1.2 -sSf https://pkgw.github.io/cranko/fetch-latest.sh | sh
      echo "##vso[task.prependpath]$d"
    displayName: Install latest Cranko

  - bash: |
      set -xeuo pipefail
      cranko release-workflow apply-versions
      git add .
      cranko release-workflow commit
      git show
    displayName: Make release commit

  - bash: |
      artifact_dir="$(Build.ArtifactStagingDirectory)/git-release"
      mkdir -p "$artifact_dir"
      git bundle create "$artifact_dir/release.bundle" origin/master..HEAD
    displayName: Bundle release commit

  - task: PublishPipelineArtifact@1
    displayName: Publish release git bundle artifact
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/git-release'
      artifactName: git-release

  # TODO: it seems that at the moment, there is no better way to create an
  # sdist than to invoke setup.py directly. People seem to be working on
  # alternatives but nothing is official yet.

  - bash: |
      set -eo pipefail  # no -u to work around Conda activatio bug (2021 July)
      eval "$($CONDA/bin/conda shell.bash hook)"
      set -x
      conda activate
      conda config --add channels conda-forge
      conda install -y \
        astropy \
        beautifulsoup4 \
        ipyevents \
        ipywidgets \
        lxml \
        matplotlib \
        numpy \
        python-dateutil \
        pytz \
        qtpy \
        reproject \
        requests \
        tornado \
        traitlets
    displayName: Set up dependencies

  - bash: |
      set -euo pipefail
      eval "$($CONDA/bin/conda shell.bash hook)"
      conda activate
      set -x
      python setup.py sdist
      tar tzf dist/*.tar.gz |sort
    displayName: Create sdist

  - task: PublishPipelineArtifact@1
    displayName: Publish sdist artifact
    inputs:
      targetPath: dist
      artifactName: sdist
